---
# Installs bash-it utilities
#  Copyright (c) 2017 Dell Inc. or its subsidiaries. All Rights Reserved.

- name: Install bash-it into workspace
  remote_user: pair
  become: no
  git:
    repo: https://github.com/Bash-it/bash-it.git
    dest: ~/.bash_it
    depth: 1

- name: Run bash-it Install
  remote_user: pair
  become: no
  shell: ~/.bash_it/install.sh --silent
  args:
    executable: /bin/bash
    creates: ~/.bash_it/plugins/enabled/base.plugin.bash

- name: copy in bash-it custom configuration
  remote_user: pair
  become: no
  copy:
    src: custom/
    dest: ~/.bash_it/custom/

- name: Update bashrc with bashit specific settings
  remote_user: pair
  become: no
  blockinfile:
    dest: .bashrc
    state: present
    insertbefore: "source .BASH_IT/bash_it.sh"
    marker: "# {mark} ANSIBLE MANAGED bash-it settings"
    block: |
      export BASH_IT_THEME='bakke'
      export SCM_GIT_SHOW_DETAILS=true
      export SCM_THEME_CURRENT_USER_PREFFIX=' ☺︎ '
  tags: [bashit, bashrc]
