---
# Install and set up git-duet

- name: Install git-duet
  unarchive:
    src: https://github.com/git-duet/git-duet/releases/download/0.5.1/linux_amd64.tar.gz
    dest: /usr/local/bin
    remote_src: True

- name: Install git-authors
  remote_user: pair
  become: no
  copy:
    src: git-authors
    dest: ~/.git-authors

- name: Update bashrc with git-duet bashrc settings
  remote_user: pair
  become: no
  blockinfile:
    dest: .bashrc
    state: present
    marker: "# {mark} ANSIBLE MANAGED git-duet settings"
    block: |
      export GIT_DUET_ROTATE_AUTHOR=1
      export GIT_DUET_GLOBAL=true
      alias dci = duet-commit
      alias drv = duet-revert
      alias dmg = duet-merge
      alias drb = rebase -i --exec 'git duet-commit --amend --reset-author'
      git config --global alias.ci duet-commit

