---
# This playbook installs terminator and its config file

- name: install terminator
  apt: name=terminator

- name: make terminator configuration dir
  remote_user: pair
  become: no
  file:
    path: ~pair/.config/terminator
    state: directory
  tags: terminator

- name: install our terminator configuration file
  remote_user: pair
  become: no
  copy:
    src: config
    dest: ~pair/.config/terminator/config
  tags: terminator
