---
# Setup the common desktop settings
#  Copyright (c) 2017 Dell Inc. or its subsidiaries. All Rights Reserved.

- name: turn screen idle value to an hour
  gsettings:
    user: pair
    key: org.gnome.desktop.session.idle-delay
    value: 7200
  tags: [ 'desktop', 'screen' ]

- name: disable screen lock
  gsettings:
    user: pair
    key: org.gnome.desktop.screensaver.{{ item }}
    value: "false"
  tags: [ 'desktop', 'screen' ]
  with_items:
    - logout-enabled
    - lock-enabled
    - ubuntu-lock-on-suspend

- name: Set hour long idle
  gsettings:
    user: pair
    key: org.gnome.desktop.screensaver.logout-delay
    value: 7200
  tags: [ 'desktop', 'screen' ]

- name: Clear lock delay
  gsettings:
    user: pair
    key: org.gnome.desktop.screensaver.lock-delay
    value: 0
  tags: [ 'desktop', 'screen' ]

- name: Add mn-lab proxy
  gsettings:
    user: pair
    key: org.gnome.system.proxy.autoconfig-url
    value: "'http://proxy.hwimo.lab.emc.com/proxy.pac'"
  tags: proxy

- name: Enable mn-lab proxy
  gsettings:
    user: pair
    key: org.gnome.system.proxy.mode
    value: "'auto'"
  tags: proxy

- name: move unity launch bar to bottom of screen
  gsettings:
    user: pair
    key: com.canonical.Unity.Launcher.launcher-position
    value: "Bottom"
  tags: desktop

# ['application://org.gnome.Nautilus.desktop', 'application://unity-control-center.desktop', 'application://terminator.desktop', 'unity://running-apps', 'application://code.desktop', 'application://slack.desktop', 'application://virtualbox.desktop', 'application://cisco-anyconnect.desktop', 'application://google-chrome.desktop', 'unity://expo-icon', 'unity://devices']

# vnc setup doesn't work yet, and I'm not sure that's what we want anyway!
#- name: enable vnc
#  gsettings:
#    user: pair
#    key: org.gnome.Vino.enabled
#    value: "true"

# - name: set vnc password
#   gsettings:
#     user: pair
#     key: org.gnome.Vino.vnc-password
#     value: ""

# - name: clear vnc prompt enabled
#   gsettings:
#     user: pair
#     key: org.gnome.Vino.prompt-enabled
#     value: "false"

# - name: set vnc auth methods
#   gsettings:
#     user: pair
#     key: org.gnome.Vino.authentication-methods
#     value: "'vnc'"

# - name: workaround for gnome bug in encryption to/from macs
#   gsettings:
#     user: pair
#     key: org.gnone.vino.require-encryption
#     value: "false"


# does not work yet
#- name: Add applications to dock
#  gsettings:
#    user: pair
#    key: com.canonical.Unity.Launcher.favorites
#    append: true
#    value: application://code.desktop