---
# Setup the common desktop settings
#  Copyright (c) 2017 Dell Inc. or its subsidiaries. All Rights Reserved.

- name: turn screen idle value to an hour
  gsettings:
    user: pair
    key: org.gnome.desktop.session.idle-delay
    value: 7200
  tags: [ 'desktop', 'screen' ]

- name: disable screen lock
  gsettings:
    user: pair
    key: org.gnome.desktop.screensaver.{{ item }}
    value: "false"
  tags: [ 'desktop', 'screen' ]
  with_items:
    - logout-enabled
    - lock-enabled
    - ubuntu-lock-on-suspend

- name: Set hour long idle
  gsettings:
    user: pair
    key: org.gnome.desktop.screensaver.logout-delay
    value: 7200
  tags: [ 'desktop', 'screen' ]

- name: Clear lock delay
  gsettings:
    user: pair
    key: org.gnome.desktop.screensaver.lock-delay
    value: 0
  tags: [ 'desktop', 'screen' ]

- name: Add mn-lab proxy
  gsettings:
    user: pair
    key: org.gnome.system.proxy.autoconfig-url
    value: "'http://proxy.hwimo.lab.emc.com/proxy.pac'"
  tags: proxy

- name: Enable mn-lab proxy
  gsettings:
    user: pair
    key: org.gnome.system.proxy.mode
    value: "'none'"
  tags: proxy

- name: move unity launch bar to bottom of screen
  gsettings:
    user: pair
    key: com.canonical.Unity.Launcher.launcher-position
    value: "'Bottom'"
  tags: desktop

- name: set up favorites app
  gsettings:
    user: pair
    key: com.canonical.Unity.Launcher.favorites
    value: "['application://org.gnome.Nautilus.desktop', 'application://remmina.desktop', 'application://unity-control-center.desktop', 'application://kde4-okular.desktop', 'application://slack.desktop', 'application://virtualbox.desktop', 'application://cisco-anyconnect.desktop', 'application://terminator.desktop', 'application://code.desktop', 'application://google-chrome.desktop', 'unity://running-apps', 'unity://expo-icon', 'unity://devices']"
  tags: desktop

- name: Setting up Okular as default pdf
  remote_user: pair
  become: no
  ini_file:
    dest: ~/.config/mimeapps.list
    section: Default Applications
    option: application/pdf
    value: kde4-okularApplication_fb.desktop
  tags: desktop

- name: Setting up Okular as default pdf
  remote_user: pair
  become: no
  ini_file:
    dest: ~/.config/mimeapps.list
    section: Added Associations
    option: application/pdf
    value: kde4-okularApplication_fb.desktop
  tags: desktop

