---
# Sets up a pairing station windows install
#  Copyright (c) 2017 Dell Inc. or its subsidiaries. All Rights Reserved.

- hosts: windows
  remote_user: pair

  tasks:
  - name: Install chocolatey for easy access to various packages
    win_shell: |
      iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))

  - name: Install choco-based applications
    win_shell: |
      choco install -y {{item}}
    with_items:
      slack
      virtual
      vagrant

  #- name: Install docker pieces
  #  win_shell: |
  #    choco install -y docker
  #    choco install -y docker-for-windows
